// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[x].tsx";
import * as $1 from "./routes/address/[address].tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/utils.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/tx/[tx].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/[x].tsx": $0,
    "./routes/address/[address].tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/utils.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/tx/[tx].tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Search.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
